version: "2.1"

services:
    wpcli:
        image: 'docker.io/bitnami/wordpress:${WP_VERSION}'
        container_name: "${PREFIX}_wpcli"
        restart: "always"
        depends_on:
            db:
                condition: service_healthy
        ports:
            - $IP:80:8080
            - $IP:443:8443
        volumes:
            - "$BUILDER_DIR/config/php.ini:/opt/bitnami/php/lib/php.ini"
            - "$PROJECT_DIR/wp:/bitnami/wordpress:consistent"
        environment:
            - MARIADB_HOST=db
            - MARIADB_PORT_NUMBER=3306
            - ALLOW_EMPTY_PASSWORD=yes
            - WORDPRESS_DATABASE_USER=wp_user
            - WORDPRESS_DATABASE_NAME=wordpress_data
            - WORDPRESS_TABLE_PREFIX=${DB_PREFIX}
            - WORDPRESS_SKIP_INSTALL=yes

    db:
        image: 'docker.io/bitnami/mariadb:10.3-debian-10'
        container_name: "${PREFIX}_mysql"
        restart: "always"
        volumes:
            - "$PROJECT_DIR/database/mysql:/bitnami/wordpress:consistent"
        environment:
            - MARIADB_USER=wp_user
            - MARIADB_DATABASE=wordpress_data
            - ALLOW_EMPTY_PASSWORD=yes
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 20

    phpmyadmin:
        image: 'docker.io/bitnami/phpmyadmin:5-debian-10'
        container_name: "${PREFIX}_phpmyadmin"
        restart: "no"
        depends_on:
            - db
        ports:
            - $IP:8000:8080
        environment:
            - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=yes
            - DATABASE_ALLOW_NO_PASSWORD=yes
            - DATABASE_HOST=db
            - DATABASE_PORT_NUMBER=3306