version: "2.1"

services:
    wpcli:
        image: 'docker.io/bitnami/wordpress:${WP_VERSION}'
        container_name: "${PREFIX}_wpcli"
        restart: "always"
        depends_on:
            - db
        ports:
            - $IP:80:8080
            - $IP:443:8443
        volumes:
            - "$BUILDER_DIR/config/php.ini:/opt/bitnami/php/lib/php.ini"
            - "$PROJECT_DIR/wp:/bitnami/wordpress:consistent"
            - "$PROJECT_DIR/logs:/opt/bitnami/apache/logs:cached"
        environment:
            - MARIADB_HOST=db
            - MARIADB_PORT_NUMBER=3306
            - WORDPRESS_DATABASE_NAME=wordpress_data
            - WORDPRESS_TABLE_PREFIX=${DB_PREFIX}
            - WORDPRESS_DATABASE_USER=wp_user
            - ALLOW_EMPTY_PASSWORD=yes
            - WORDPRESS_SKIP_INSTALL=yes
            # - WORDPRESS_RESET_DATA_PERMISSIONS=yes
            - WORDPRESS_SCHEME=http
            - WORDPRESS_USERNAME=${DEVELOPER_USERNAME}
            - WORDPRESS_PASSWORD=projector
            - WORDPRESS_EMAIL=${DEVELOPER_EMAIL}
            - WORDPRESS_FIRST_NAME=${DEVELOPER_NAME}
            - WORDPRESS_LAST_NAME=${DEVELOPER_LAST_NAME}
            - WORDPRESS_BLOG_NAME=${NAME}

    db:
        image: 'docker.io/bitnami/mariadb:10.3-debian-10'
        container_name: "${PREFIX}_mysql"
        restart: "always"
        volumes:
            - "$PROJECT_DIR/database/mysql:/bitnami/mariadb:consistent"
        environment:
            - MARIADB_USER=wp_user
            - MARIADB_DATABASE=wordpress_data
            - ALLOW_EMPTY_PASSWORD=yes

    phpmyadmin:
        image: 'docker.io/bitnami/phpmyadmin:5-debian-10'
        container_name: "${PREFIX}_phpmyadmin"
        restart: "no"
        depends_on:
            - db
        ports:
            - $IP:8000:8080
        environment:
            - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=yes
            - DATABASE_ALLOW_NO_PASSWORD=yes
            - DATABASE_HOST=db
            - DATABASE_PORT_NUMBER=3306