#!/bin/bash

# Builder directory
BUILDERDIR=~/Desktop/projector
source "$BUILDERDIR/global.sh"




# Check if current folder is a project folder (project-name/)
if [[ -f "${BASEDIR}/local.env" ]] || [[ -f "${BASEDIR}/.env" ]]; then


	# Extract the project name from BASEDIR
	SLUG="${BASEDIR%"${BASEDIR##*[!/]}"}"
	SLUG="${SLUG##*/}"
	#echo "Project name: $SLUG"


	# Project directory
	PROJECTDIR=$BASEDIR


fi # If current folder is a project folder


# wp --info
# exit



# Ask for the action, if not specified
ACTION=$1
if [[ -z $ACTION ]]; then


	echo ""
	echo ""
	echo "== Allowed Actions ===================="
	echo ""
	echo -e "${BLUE}starter${RESET} - Create a new project from scratch"
	echo -e "${BLUE}clone${RESET} - Clone a project from BitBucket"
	echo -e "${BLUE}install${RESET} - Install a project that already clonned or created"
	echo -e "${BLUE}uninstall${RESET} - Uninstall a project that already installed"
	echo -e "${BLUE}start${RESET} - Run the server and Node JS of an installed project"
	echo -e "${BLUE}stop${RESET} - Stop the servers of an installed project"
	echo -e "${BLUE}pull${RESET} - Pull the latest changes from Git"
	echo -e "${BLUE}push${RESET} - Push the latest local changes to Git"
	echo -e "${BLUE}permission-fix${RESET} - If you get permission errors, do this"
	echo -e "${BLUE}import${RESET} - Import an existing files to a project"
	echo ""
	echo "================================="
	echo ""

	read -ep "Write the action type: " ACTION
	if [[ -z $ACTION ]]; then

		echo -e "${RED}No action entered.${RESET}"
		exit

	fi


fi


# If unknown answer
if [[ $ACTION != starter ]] && [[ $ACTION != clone ]] && [[ $ACTION != install ]] && [[ $ACTION != uninstall ]] && [[ $ACTION != start ]] && [[ $ACTION != stop ]] && [[ $ACTION != pull ]] && [[ $ACTION != push ]] && [[ $ACTION != permission-fix ]] && [[ $ACTION != import ]]; then

	echo -e "${RED}Wrong action.${RESET}"
	exit

fi




# If it's under current folder (Projects/project-name)
if [[ -z $SLUG ]] && [[ -z $PROJECTDIR ]]; then


	# Get project name from args
	if [[ ! -z $2 ]]; then

		SLUG=$2

	else


		# Ask for the project name
		read -ep "Project name (site-name): " SLUG
		while [[ -z $SLUG ]]; do
			read -ep "Project name (site-name): " SLUG
		done


	fi


	# Project directory
	PROJECTDIR="${BASEDIR}/${SLUG}"


fi




# Installation Check
INSTALLED="no"
if [[ -f "$PROJECTDIR/.env" ]]; then


	# Get data from .env file
	source "$PROJECTDIR/.env"


	if [[ $IP != "127.0.0.1" ]]; then

		INSTALLED="yes"

	fi # If already installed


fi # If has an .env file




## DO THE ACTION:
if [[ -f "$BUILDERDIR/actions/$ACTION" ]]; then

	source "$BUILDERDIR/actions/$ACTION"

fi