#!/bin/bash

# Builder directory
BUILDERDIR=builderdir


# Check if the builder exists
if [[ -f "$BUILDERDIR/projector" ]]; then


	# Check update
	(
		cd "$BUILDERDIR"
		printf "Checking updates ..."
		git reset --hard origin/master --quiet
		git clean -df origin/master --quiet
		if git pull origin master --no-commit --quiet; then

			echo -e " ${GREEN}done${RESET}"

		else

			echo -e " ${RED}error${RESET}"

		fi
	)


	# Early access to the root
	sudo true


	# Check the sudo access to run the app
	if [ "$(sudo -n uptime 2>&1|grep "load"|wc -l)" -gt 0 ]; then

		# Run the app
		source "$BUILDERDIR/projector"

	else
		exit
	fi


else


	echo -e "${RED}Builder folder has been moved or deleted. Please install PROJECTOR again.${RESET}"
	exit


fi