#!/bin/bash


# Check if the project folder already exists
if [[ -d "$PROJECTDIR" ]]; then

	echo -e "${RED}Project folder already exist.${RESET}"
	exit

fi




# Test the git URL
if git ls-remote "https://twelve12com@bitbucket.org/twelve12com/$SLUG.git" HEAD &>/dev/null; then

	echo -e "${GREEN}Repository found, clone starting for '$SLUG' project.${RESET}"

else

	echo -e "${RED}Remote repository not found for '$SLUG' project.${RESET}"
	exit

fi




# Clone the repo
git clone "https://twelve12com@bitbucket.org/twelve12com/$SLUG.git" "$PROJECTDIR"
echo -e "Cloning '$SLUG' project ... ${GREEN}done${RESET}"




# START THE INSTALLATION
read -ep "Project has been clonned but not installed. Would you like to install it? (Press 'enter' or type 'no'): " confirm
if [[ $confirm != "no" ]]; then

	# Get environmental data
	get_env_data

	source "$BUILDERDIR/actions/install"

else

	echo -e "${RED}Not installed.${RESET}"
	exit

fi
