#!/bin/bash




# Check if the folder not exists
if [[ ! -d "$PROJECTDIR" ]]; then

	echo -e "${RED}Project doesn't exist.${RESET}"
	exit

fi




# Check if installed
if [[ $INSTALLED != "yes" ]]; then

	echo -e "${RED}Project is not installed.${RESET}"
	exit

fi




echo "EXPORTING STARTED"




# Ask for the target domain
while [[ -z "$targetdomain" ]]; do

	read -ep "Target domain (www.domainname.com): " targetdomain

done




# Ask for the target protocol
while [[ $targetprotocol != http ]] && [[ $targetprotocol != https ]]; do

	read -ep "Target protocol (http | https): " targetprotocol

done




# Backup the current DB
wp db export "tmp_wordpress_data.sql"


# Check the initial backup file
if [[ ! -f "$PROJECTDIR/wp/tmp_wordpress_data.sql" ]]; then

	echo -e "${RED}DB backup not found.${RESET}"
	exit

fi




# Do the replacements
echo -e "Replacement 1 starting... '${BLUE}http://${DOMAIN}${RESET}' -> '${BLUE}${targetprotocol}://${targetdomain}${RESET}'"
wp search-replace "http://${DOMAIN}" "${targetprotocol}://${targetdomain}" --recurse-objects --report-changed-only --all-tables
echo -e "Replacement 1 ... ${GREEN}done${RESET}"

echo -e "Replacement 2 starting... '${BLUE}${DOMAIN}${RESET}' -> '${BLUE}${targetdomain}${RESET}'"
wp search-replace "${DOMAIN}" "${targetdomain}" --recurse-objects --report-changed-only --all-tables
echo -e "Replacement 2 ... ${GREEN}done${RESET}"


# Backup after replacements
wp db export "live.sql"


# Revert the DB
wp db import "tmp_wordpress_data.sql"
sudo rm -rf "$PROJECTDIR/wp/tmp_wordpress_data.sql"


# Check the replaced backup file
if [[ ! -f "$PROJECTDIR/wp/live.sql" ]]; then

	echo -e "${RED}CHANGED SQL FILE NOT FOUND.${RESET}"
	exit

fi




# Remove existing "export" folder
sudo rm -rf "$PROJECTDIR/export"




# Create the export folder
mkdir -p "$PROJECTDIR/export"




# Move the SQL file
sudo mv "$PROJECTDIR/wp/live.sql" "$PROJECTDIR/export/live.sql"




# Copy the theme folder
sudo cp -rf "$PROJECTDIR/wp/wp-content/themes/$SLUG" "$PROJECTDIR/export/$SLUG"




# Delete 'node_modules' folder if exists
sudo rm -rf "$PROJECTDIR/export/$SLUG/node_modules"




# Delete 'package-lock.json' file if exists
sudo rm -rf "$PROJECTDIR/export/$SLUG/package-lock.json"




# Zip the folder
echo -e "Zipping the theme folder..."
(
	cd "$PROJECTDIR/export"
	zip -r -X "$SLUG.zip" "$SLUG"
)
echo -e "'$SLUG.zip' theme file created ... ${GREEN}done${RESET}"




# Remove the theme folder
sudo rm -rf "$PROJECTDIR/export/$SLUG"
echo -e "Theme folder removed ... ${GREEN}done${RESET}"




# Permission fix on 'export' folder
permission_update "$PROJECTDIR/export"




echo -e "${GREEN}EXPORTING COMPLETE${RESET}"