#!/bin/bash


# Git permissions update
if [[ $OPTION1 == --all ]] || [[ $OPTION1 == --git ]]; then

	git_permission_update "$PROJECTDIR/.git"

fi


# Server permission update
if [[ $OPTION1 == --all ]] || [[ $OPTION1 == --server ]]; then

	# server_permission_update "/var/www/html"

fi


# Local file permission update
if [[ $OPTION1 == --all ]] || [[ $OPTION1 == --permission ]]; then

	permission_update "$PROJECTDIR"

fi


# Site folder permission update
if [[ -z $OPTION1 ]]; then

	git_permission_update "$PROJECTDIR/.git"
	permission_update "$PROJECTDIR/wp/wp-content"

fi