#!/bin/bash




# Check if the folder not exists
if [[ ! -d "$PROJECTDIR" ]]; then

	echo -e "${RED}Project doesn't exist.${RESET}"
	exit

fi




# Check if installed
if [[ $INSTALLED != "yes" ]]; then


	read -ep "Project is not installed. Would you like to install it first? (yes | no): " confirm
	if [[ $confirm == "yes" ]] || [[ $confirm == "y" ]]; then

		source "$BUILDERDIR/actions/install"

	fi


fi




# Check if container exists
if [[ $CONTAINEREXISTS != "yes" ]]; then

	echo -e "${RED}Containers not found. Please re-install the project.${RESET}"
	exit

fi




# Wordpress Version Check on Docker Hub
printf "Checking Wordpress ${WP_VERSION} availability ..."
if ! version_check $WP_VERSION; then

	echo -e " ${RED}not available${RESET}"
	exit

fi
echo -e " ${GREEN}available${RESET}"




# Restore file removal
if [[ -f "$PROJECTDIR/wp/.restored" ]]; then

	rm "$PROJECTDIR/wp/.restored"

fi




# Restart the server
run_server "reinstall"




# Fix the site git permissions
if [[ -d "$PROJECTDIR/.git" ]]; then

	git_permission_update "$PROJECTDIR/.git"

fi




# PRINT THE SITE INFO
echo -e "${GREEN}Site is up!${RESET}"
echo ""
echo ""
echo "== Site Info ===================="
echo ""
echo "Local URL: http://${DOMAIN}"
echo "Local IP: ${IP}"
echo ""
echo "================================="
echo ""
echo ""




# Open the link in browser
source "$BUILDERDIR/actions/open"