#!/bin/bash




# Check if the folder not exists
if [[ ! -d "$PROJECTDIR" ]]; then

	echo -e "${RED}Project doesn't exist.${RESET}"
	exit

fi




# Check if installed
if [[ $INSTALLED != "yes" ]]; then


	read -ep "Project is not installed. Would you like to install it first? (yes | no): " confirm
	if [[ $confirm == "yes" ]] || [[ $confirm == "y" ]]; then

		source "$BUILDERDIR/actions/install"

	else

		echo -e "${RED}Continue without installing the project.${RESET}"

	fi


else


	# Check if container exists
	if [[ $CONTAINEREXISTS != "yes" ]]; then

		echo -e "${RED}Containers not found. Please re-install the project.${RESET}"
		exit

	fi




	# Run the server
	run_server_if_not_running




	# Check MySQL to be ready
	wait_for_mysql




	# Pull the changes and start
	PERMISSIONFIX="no"
	source "$BUILDERDIR/actions/pull"




	# PRINT THE SITE INFO
	echo -e "${GREEN}Site is up!${RESET}"
	echo ""
	echo ""
	echo "== Site Info ===================="
	echo ""
	echo "Local URL: http://${DOMAIN}"
	echo "Local IP: ${IP}"
	echo ""
	echo "================================="
	echo ""
	echo ""


fi




# Install NPM for Gulp
if [[ $OPTION1 != --nonode ]]; then

	install_npm

fi