#!/bin/bash




# Check if the folder not exists
if [[ ! -d $PROJECTDIR ]]; then

	echo -e "${RED}Project doesn't exist.${RESET}"
	exit

fi




# Check if installed
if [[ $INSTALLED != "yes" ]]; then


	echo -e "${RED}Project is not installed.${RESET}"
	exit


fi




# Open that IP slot
ifconfig lo0 alias $IP up
echo -e "'${IP}' is now available ... ${GREEN}done${RESET}"




# Run the server
run_server_if_not_running




# Check MySQL to be ready
wait_for_mysql




# Pull the changes and start (optionally --hard)
source "$BUILDERDIR/actions/pull"




# PRINT THE SITE INFO
echo -e "${GREEN}Site is up!${RESET}"
echo ""
echo ""
echo "== Site Info ===================="
echo ""
echo "Admin Page: http://${DOMAIN}"
echo "IP: ${IP}"
echo ""
echo "================================="
echo ""
echo ""




# Install NPM for Gulp
install_npm