#!/bin/bash




# Check if the folder not exists
if [[ ! -d "$PROJECTDIR" ]]; then

	echo -e "${RED}Project doesn't exist.${RESET}"
	exit

fi




# Check if installed
if [[ $INSTALLED != "yes" ]]; then

	echo -e "${RED}Project is not installed.${RESET}"
	exit

fi




# Check if container exists
if [[ $CONTAINEREXISTS != "yes" ]]; then

	echo -e "${RED}Containers not found. Please re-install the project.${RESET}"
	exit

fi




# Check if container is running
if [[ $CONTAINERRUNNING != "yes" ]]; then

	echo -e "${RED}Cannot stop because containers are not running.${RESET}"
	exit

fi




# Stop the server
echo "Server is stopping..."
docker_compose stop