#!/bin/bash




# Check if the folder not exists
if [[ ! -d "$PROJECTDIR" ]]; then

	echo -e "${RED}Project doesn't exist.${RESET}"
	exit

fi


# Check if the folder is not a project folder
if [[ ! -f "$PROJECTDIR/.env" ]] && [[ ! -f "$PROJECTDIR/local.env" ]]; then

	echo -e "${RED}This is not a project folder.${RESET}"
	exit

fi


# Pre-confirm
if [[ $OPTION1 == -y ]] || [[ $OPTION2 == -y ]]; then

	confirm=yes

fi



if [[ -z $confirm ]] || [[ $confirm != "yes" ]]; then


	read -ep "Are you sure you want to uninstall the '$SLUG' project? (yes | no): " confirm
	if [[ $confirm != yes ]] && [[ $confirm != y ]]; then

		echo -e "${RED}Not confirmed.${RESET}"
		exit

	fi


fi




# Check if installed
if [[ $INSTALLED != "yes" ]]; then

	echo -e "${RED}Project is not installed. But still trying to remove...${RESET}"

fi




# Get environmental data
get_env_data




# Create and Update environment files
update_environment




## UNINSTALLATION:

# Optional: Do not get backup
if [[ $OPTION1 != --nobackup ]] && [[ $OPTION2 != --nobackup ]] && [[ $OPTION1 != --remove ]] && [[ $OPTION2 != --remove ]]; then


	# Save a DB backup first
	db_backup


fi




# Close the server
echo "Server is closing..."
docker_compose down --volumes --remove-orphans




# Remove the host to the list
sudo bash "$BUILDERDIR/config/etc-hosts.sh" -remove $DOMAIN
#killall -HUP mDNSResponder




# Remove WP core files
printf "Removing WP core files ..."
(
	cd "$PROJECTDIR/wp"
	find . -mindepth 1 -maxdepth 1 ! -name 'wp-content' -exec sudo rm -rf '{}' \;
)
echo -e " ${GREEN}done${RESET}"




# Delete the .env file
sudo rm -rf "$PROJECTDIR/.env"
echo -e ".env file removed from the project ... ${GREEN}done${RESET}"




# Optional: Remove the folder
if [[ $OPTION1 == --remove ]] || [[ $OPTION2 == --remove ]]; then


	printf "Removing project folder ..."
	sudo rm -rf "$PROJECTDIR"
	echo -e " ${GREEN}done${RESET}"


fi




# DEFAULT PROJECT STATUSES
INSTALLED="no"
CONTAINEREXISTS="no"
CONTAINERRUNNING="no"




echo -e "Uninstalling '$SLUG' project ... ${GREEN}done${RESET}"
