#!/bin/bash




# Check if the folder not exists
if [[ ! -d $PROJECTDIR ]]; then

	echo -e "${RED}Project doesn't exist.${RESET}"
	exit

fi




# Check if installed
if [[ $INSTALLED != "yes" ]]; then

	echo -e "${RED}Project is not installed.${RESET}"

fi




# Get environmental data
get_env_data




# Create and Update environment files
update_environment




## UNINSTALLATION:

# Save a DB backup first
db_backup




echo "Server is closing..."
docker_compose down




# Remove the host to the list
sudo bash "$BUILDERDIR/config/etc-hosts.sh" -remove $DOMAIN
killall -HUP mDNSResponder



# Delete the DB files
rm -rf "$PROJECTDIR/database/mysql"
echo -e "MySQL files removed ... ${GREEN}done${RESET}"



# Remove WP core files
(
	cd "$PROJECTDIR/wp"
	find . -mindepth 1 -maxdepth 1 ! -name 'wp-content' -exec rm -rf '{}' \;
)
echo -e "WP core files removed ... ${GREEN}done${RESET}"




# Delete the .env file
rm -rf "$PROJECTDIR/.env"
echo -e ".env file removed from the project ... ${GREEN}done${RESET}"



# Remove the folder
if [[ $OPTION1 == --remove ]]; then


	echo -e "Project folder removing..."
	rm -rf "$PROJECTDIR"
	echo -e "Project folder removed ... ${GREEN}done${RESET}"


fi




echo -e "Uninstalling '${SLUG}' project ... ${GREEN}done${RESET}"
